name: DiskANN Push Build
on: [push]
jobs:
  ubuntu-latest-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt install cmake g++ libaio-dev libgoogle-perftools-dev libunwind-dev clang-format libboost-dev libboost-program-options-dev libmkl-full-dev libcpprest-dev
    - name: Clang Format Check
      run: |
        mkdir build && cd build && cmake -DRESTAPI=True -DCMAKE_BUILD_TYPE=Release ..
        make checkformat
    - name: build
      run: |
        cd build && make -j
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Python Build Module
      run: python -m pip install build
    - name: Python Build
      run: python -m build